### ISSUE TITLE
CodingKeys Enum Obfuscation Error

### ISSUE THREAD

**Issue by joelpjy** [rockbruno/swiftshield#88] opened 2020-01-21 08:16 UTC
Hi, I was using the lastest version of swiftshield to obfuscate my app.

I saw the update about obfuscating enums except CodingKeys.
However, the contents of the CodingKeys enum is still being obfuscated.

Example before obfuscation:
```
class SampleClass: Codable {
    var name: String? = ""
    var age: String? = ""
  
    enum CodingKeys: String, CodingKey {
        case name = "name"
        case age = "age"
    }
}
```

After obfuscation:
```
class TTsyOuzUyPjxhNaeoRsItQrJPqSnWwep: Codable {
    var name: String? = ""
    var age: String? = ""
  
    enum CodingKeys: String, CodingKey {
        case SQOCQFwmJlerAkdYxJxOAWQbfxJPJrOf = "name"  //suppose to be case name = "name"
        case WTxcFuKTOoUlNMxwMuSBncSvErQNreIg = "age"  //suppose to be case age = "age"
    }
}

```

is the contents of CodingKeys enums meant to be obfuscated? Cause this is currently causing a compile error after obfuscation. (Does not conform to the Codable protocol)

**Comment by rockbruno** [comment] 2020-01-21 11:02
@hwdavr Any idea what could have caused this?

**Comment by hwdavr** [comment] 2020-01-21 11:18
@joelpjy Could you upload the obfuscation log for us to analysis?

**Comment by rockbruno** [comment] 2020-01-21 11:20
I would guess that our `usrWithoutSuffix` approach failed here... Hopefully the logs will shows us more

**Comment by hwdavr** [comment] 2020-01-21 11:23
YUp, could be, maybe original implementation is better, let's see.

**Comment by joelpjy** [comment] 2020-01-22 02:20
Hi, sorry for the late reply.
I've created a sample project you can download and try. (https://github.com/joelpjy/TestSwiftShield)

I used the command:
`./swiftshield -automatic -project-root Testing -automatic-project-file Testing/TestSwiftShield.xcworkspace -automatic-project-scheme TestSwiftShield`

Output Log:
```
TestSwiftShield
SwiftShield 3.5.0
Automatic mode
Building project to gather modules and compiler arguments...
-- Indexing ViewController.swift --
Found declaration of ViewController (c:@M@TestSwiftShield@objc(cs)ViewController)
Found declaration of viewDidLoad (c:@M@TestSwiftShield@objc(cs)ViewController(im)viewDidLoad)
-- Indexing UserCodable.swift --
Found declaration of User (s:15TestSwiftShield4UserC)
Found declaration of name (s:15TestSwiftShield4UserC10CodingKeysO4nameyA2EmF)
Found declaration of age (s:15TestSwiftShield4UserC10CodingKeysO3ageyA2EmF)
-- Indexing AppDelegate.swift --
Found declaration of AppDelegate (c:@M@TestSwiftShield@objc(cs)AppDelegate)
Found declaration of application (c:@M@TestSwiftShield@objc(cs)AppDelegate(im)application:didFinishLaunchingWithOptions:)
Found declaration of application (c:@M@TestSwiftShield@objc(cs)AppDelegate(im)application:configurationForConnectingSceneSession:options:)
Found declaration of application (c:@M@TestSwiftShield@objc(cs)AppDelegate(im)application:didDiscardSceneSessions:)
-- Indexing SceneDelegate.swift --
Found declaration of SceneDelegate (c:@M@TestSwiftShield@objc(cs)SceneDelegate)
Found declaration of scene (c:@M@TestSwiftShield@objc(cs)SceneDelegate(im)scene:willConnectToSession:options:)
Found declaration of sceneDidDisconnect (c:@M@TestSwiftShield@objc(cs)SceneDelegate(im)sceneDidDisconnect:)
Found declaration of sceneDidBecomeActive (c:@M@TestSwiftShield@objc(cs)SceneDelegate(im)sceneDidBecomeActive:)
Found declaration of sceneWillResignActive (c:@M@TestSwiftShield@objc(cs)SceneDelegate(im)sceneWillResignActive:)
Found declaration of sceneWillEnterForeground (c:@M@TestSwiftShield@objc(cs)SceneDelegate(im)sceneWillEnterForeground:)
Found declaration of sceneDidEnterBackground (c:@M@TestSwiftShield@objc(cs)SceneDelegate(im)sceneDidEnterBackground:)
-- Searching for references of the retrieved USRs --
Found ViewController (c:@M@TestSwiftShield@objc(cs)ViewController) at ViewController.swift (L:11 C: 7 -> now qPYQKoiWTuRrpFtAUplpyfSyEfHKeweP)
Found User (s:15TestSwiftShield4UserC) at ViewController.swift (L:16 C: 22 -> now cTtUHfRbEnRXtrccueomOjuiDdbhcHNK)
Found User (s:15TestSwiftShield4UserC) at ViewController.swift (L:16 C: 29 -> now cTtUHfRbEnRXtrccueomOjuiDdbhcHNK)
Found User (s:15TestSwiftShield4UserC) at UserCodable.swift (L:11 C: 7 -> now cTtUHfRbEnRXtrccueomOjuiDdbhcHNK)
Found name (s:15TestSwiftShield4UserC10CodingKeysO4nameyA2EmF) at UserCodable.swift (L:22 C: 14 -> now IYNXkQCzyKiModhWgWmrfiHegdxVUUHb)
Found age (s:15TestSwiftShield4UserC10CodingKeysO3ageyA2EmF) at UserCodable.swift (L:23 C: 14 -> now GOXTfTkRqqyQPERprUjSFmXInmlYWKch)
Found AppDelegate (c:@M@TestSwiftShield@objc(cs)AppDelegate) at AppDelegate.swift (L:12 C: 7 -> now OcvuhHMXuZbzEYZSocKxVYdgzyFizGdV)
Found SceneDelegate (c:@M@TestSwiftShield@objc(cs)SceneDelegate) at SceneDelegate.swift (L:11 C: 7 -> now ndEkKTGYAhJmxzMksniRikgDrUXbGbzg)
--- Overwriting ViewController.swift ---
--- Overwriting SceneDelegate.swift ---
--- Overwriting UserCodable.swift ---
--- Overwriting AppDelegate.swift ---
--- Overwriting Storyboards ---
--- Checking LaunchScreen.storyboard ---
--- Checking Main.storyboard ---
--- Generating conversion map ---
-- Adding SWIFTSHIELDED=true to projects --
Finished.

```

**Comment by hwdavr** [comment] 2020-01-22 16:06
@rockbruno Seems the issue is because the USR doesn't has the underscore. I think we have to revert back to previous implementation.

**Comment by rockbruno** [comment] 2020-05-22 19:17
I'll close it as its fixed. I just made some performance improvements as well.

**Closed by rockbruno** 2020-05-22 19:17 UTC
